services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - microservices-net

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: gosqu
      POSTGRES_PASSWORD: gosqu
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    restart: unless-stopped

networks:
    microservices-net:
        driver: bridge

volumes:
  postgres:
